/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */
package setting;

import bridging.BridgingWA;
import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import groovy.lang.Sequence;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author perpustakaan
 */
public class DlgPindahRiwPasien extends javax.swing.JDialog {

    private validasi Valid = new validasi();
    private BridgingWA kirimwa = new BridgingWA();
    private sekuel Sequel = new sekuel();
    private String addquery = "";

    /**
     * Creates new form DlgAdmin
     *
     * @param parent
     * @param modal
     */
    public DlgPindahRiwPasien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10, 10);
        setSize(457, 249);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        panelGlass7 = new widget.panelisi();
        jLabel3 = new widget.Label();
        NoRwDari = new widget.TextBox();
        jLabel4 = new widget.Label();
        scrollPane1 = new widget.ScrollPane();
        pesan = new widget.TextArea();
        BtnKeluar = new widget.Button();
        BtnCek = new widget.Button();
        jLabel5 = new widget.Label();
        NoRwKe = new widget.TextBox();
        jLabel6 = new widget.Label();
        scrollPane2 = new widget.ScrollPane();
        pesan1 = new widget.TextArea();
        BtnKeluar1 = new widget.Button();
        jLabel8 = new widget.Label();
        DTPTgl = new widget.Tanggal();
        jLabel9 = new widget.Label();
        CmbJam = new widget.ComboBox();
        CmbMenit = new widget.ComboBox();
        CmbDetik = new widget.ComboBox();
        chkSemua = new widget.CekBox();
        noresep = new widget.TextBox();
        jLabel12 = new widget.Label();
        cmbJenis = new widget.ComboBox();
        jLabel7 = new widget.Label();
        jLabel10 = new widget.Label();
        jLabel11 = new widget.Label();
        BtnBatal = new widget.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ Pindah Riwayat Pasien ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(70, 70, 70))); // NOI18N
        internalFrame1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass7.setName("panelGlass7"); // NOI18N
        panelGlass7.setPreferredSize(new java.awt.Dimension(44, 547));
        panelGlass7.setLayout(null);

        jLabel3.setText("Dari No. Rawat :");
        jLabel3.setName("jLabel3"); // NOI18N
        panelGlass7.add(jLabel3);
        jLabel3.setBounds(0, 12, 100, 23);

        NoRwDari.setHighlighter(null);
        NoRwDari.setName("NoRwDari"); // NOI18N
        panelGlass7.add(NoRwDari);
        NoRwDari.setBounds(105, 10, 280, 23);

        jLabel4.setText("Text :");
        jLabel4.setName("jLabel4"); // NOI18N
        panelGlass7.add(jLabel4);
        jLabel4.setBounds(0, 40, 100, 23);

        scrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPane1.setName("scrollPane1"); // NOI18N

        pesan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pesan.setColumns(20);
        pesan.setRows(5);
        pesan.setName("pesan"); // NOI18N
        scrollPane1.setViewportView(pesan);

        panelGlass7.add(scrollPane1);
        scrollPane1.setBounds(105, 40, 280, 80);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setIconTextGap(3);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass7.add(BtnKeluar);
        BtnKeluar.setBounds(750, 350, 100, 30);

        BtnCek.setMnemonic('S');
        BtnCek.setText("Cek Data");
        BtnCek.setToolTipText("Alt+S");
        BtnCek.setName("BtnCek"); // NOI18N
        BtnCek.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCekActionPerformed(evt);
            }
        });
        BtnCek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCekKeyPressed(evt);
            }
        });
        panelGlass7.add(BtnCek);
        BtnCek.setBounds(780, 10, 110, 23);

        jLabel5.setText("Ke No. Rawat :");
        jLabel5.setName("jLabel5"); // NOI18N
        panelGlass7.add(jLabel5);
        jLabel5.setBounds(390, 10, 100, 23);

        NoRwKe.setHighlighter(null);
        NoRwKe.setName("NoRwKe"); // NOI18N
        panelGlass7.add(NoRwKe);
        NoRwKe.setBounds(495, 10, 280, 23);

        jLabel6.setText("Text :");
        jLabel6.setName("jLabel6"); // NOI18N
        panelGlass7.add(jLabel6);
        jLabel6.setBounds(390, 40, 100, 23);

        scrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPane2.setName("scrollPane2"); // NOI18N

        pesan1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pesan1.setColumns(20);
        pesan1.setRows(5);
        pesan1.setName("pesan1"); // NOI18N
        scrollPane2.setViewportView(pesan1);

        panelGlass7.add(scrollPane2);
        scrollPane2.setBounds(495, 40, 280, 80);

        BtnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/edit_f2.png"))); // NOI18N
        BtnKeluar1.setMnemonic('K');
        BtnKeluar1.setText("Pindah");
        BtnKeluar1.setToolTipText("Alt+K");
        BtnKeluar1.setIconTextGap(3);
        BtnKeluar1.setName("BtnKeluar1"); // NOI18N
        BtnKeluar1.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluar1ActionPerformed(evt);
            }
        });
        BtnKeluar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluar1KeyPressed(evt);
            }
        });
        panelGlass7.add(BtnKeluar1);
        BtnKeluar1.setBounds(450, 350, 100, 30);

        jLabel8.setText("Tgl :");
        jLabel8.setName("jLabel8"); // NOI18N
        panelGlass7.add(jLabel8);
        jLabel8.setBounds(10, 250, 60, 23);

        DTPTgl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20-03-2024" }));
        DTPTgl.setDisplayFormat("dd-MM-yyyy");
        DTPTgl.setName("DTPTgl"); // NOI18N
        DTPTgl.setOpaque(false);
        DTPTgl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DTPTglItemStateChanged(evt);
            }
        });
        DTPTgl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DTPTglMouseClicked(evt);
            }
        });
        DTPTgl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DTPTglKeyPressed(evt);
            }
        });
        panelGlass7.add(DTPTgl);
        DTPTgl.setBounds(80, 250, 90, 23);

        jLabel9.setText("Jam :");
        jLabel9.setName("jLabel9"); // NOI18N
        panelGlass7.add(jLabel9);
        jLabel9.setBounds(170, 250, 36, 23);

        CmbJam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        CmbJam.setName("CmbJam"); // NOI18N
        CmbJam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbJamKeyPressed(evt);
            }
        });
        panelGlass7.add(CmbJam);
        CmbJam.setBounds(210, 250, 62, 23);

        CmbMenit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        CmbMenit.setName("CmbMenit"); // NOI18N
        CmbMenit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbMenitKeyPressed(evt);
            }
        });
        panelGlass7.add(CmbMenit);
        CmbMenit.setBounds(275, 250, 62, 23);

        CmbDetik.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        CmbDetik.setName("CmbDetik"); // NOI18N
        CmbDetik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CmbDetikKeyPressed(evt);
            }
        });
        panelGlass7.add(CmbDetik);
        CmbDetik.setBounds(340, 250, 62, 23);

        chkSemua.setBorder(null);
        chkSemua.setText("Pindah Semua Riwayat");
        chkSemua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chkSemua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        chkSemua.setName("chkSemua"); // NOI18N
        chkSemua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSemuaActionPerformed(evt);
            }
        });
        panelGlass7.add(chkSemua);
        chkSemua.setBounds(40, 220, 150, 23);

        noresep.setHighlighter(null);
        noresep.setName("noresep"); // NOI18N
        panelGlass7.add(noresep);
        noresep.setBounds(480, 250, 150, 23);

        jLabel12.setText("No. Resep :");
        jLabel12.setName("jLabel12"); // NOI18N
        panelGlass7.add(jLabel12);
        jLabel12.setBounds(405, 250, 70, 23);

        cmbJenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1. Resep Obat Ralan", "2. Resep Obat Ranap", "3. Resep Pulang", "4. SOAP Ralan", "5. Soap Ranap", "6. Laboratorium", "7. Radiologi", "8. Registrasi", "9. SEP", "10. SPRI", "11. Triage IGD", "12. Tindakan Dokter Ralan", "13. Tindakan Paramedis Ralan", "14. Transfer Pasien", " " }));
        cmbJenis.setName("cmbJenis"); // NOI18N
        cmbJenis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbJenisItemStateChanged(evt);
            }
        });
        cmbJenis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbJenisKeyPressed(evt);
            }
        });
        panelGlass7.add(cmbJenis);
        cmbJenis.setBounds(190, 220, 260, 23);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Catatan:");
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        panelGlass7.add(jLabel7);
        jLabel7.setBounds(40, 150, 360, 23);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("*Untuk pindah riwayat Lab/Radiologi gunakan Tanggal dan Jam Periksa");
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        panelGlass7.add(jLabel10);
        jLabel10.setBounds(40, 190, 420, 23);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("*Untuk pindah riwayat obat gunakan Tanggal dan Jam Validasi");
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        panelGlass7.add(jLabel11);
        jLabel11.setBounds(40, 170, 360, 23);

        BtnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Cancel-2-16x16.png"))); // NOI18N
        BtnBatal.setMnemonic('B');
        BtnBatal.setText("Baru");
        BtnBatal.setToolTipText("Alt+B");
        BtnBatal.setName("BtnBatal"); // NOI18N
        BtnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });
        panelGlass7.add(BtnBatal);
        BtnBatal.setBounds(550, 350, 100, 30);

        internalFrame1.add(panelGlass7, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCekActionPerformed
        if (cekSttsBayar(NoRwDari.getText()).equals("Sudah Bayar") || cekSttsBayar(NoRwKe.getText()).equals("Sudah Bayar")) {
            JOptionPane.showMessageDialog(null, "Data pasien sudah closing..!!!");
        } else if (cekSttsBayar(NoRwDari.getText()).equals("")) {
            JOptionPane.showMessageDialog(null, "No. Rawat " + NoRwDari.getText() + " tidak ditemukan!");
        } else if (cekSttsBayar(NoRwKe.getText()).equals("")) {
            JOptionPane.showMessageDialog(null, "No. Rawat " + NoRwKe.getText() + " tidak ditemukan!");
        } else {
            pesan.setText(cekData(NoRwDari.getText()));
            pesan1.setText(cekData(NoRwKe.getText()));
        }
}//GEN-LAST:event_BtnCekActionPerformed

    private void BtnCekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCekKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCekActionPerformed(null);
        } else {
            Valid.pindah(evt, NoRwDari, pesan);
        }
}//GEN-LAST:event_BtnCekKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        } else {
            Valid.pindah(evt, pesan, BtnKeluar);
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void BtnKeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluar1ActionPerformed
        String text = "";
        if (chkSemua.isSelected() == true) {
            text = " SEMUA ";
        } else {
            text = " ";
        }
        if (NoRwKe.getText().equals("") || NoRwDari.getText().equals("")) {
            Valid.textKosong(NoRwKe, "No.Rawat");
        } else {
            int reply = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin memindah" + text + "riwayat pasien \n dari " + NoRwDari.getText() + " ke " + NoRwKe.getText() + "...???", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {
                if (chkSemua.isSelected() == true) {
                    pindahAll();
                }
                if (chkSemua.isSelected() == false) {
                    pindah();
                }
            }
        }
    }//GEN-LAST:event_BtnKeluar1ActionPerformed

    private void BtnKeluar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKeluar1KeyPressed

    private void DTPTglItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DTPTglItemStateChanged

    }//GEN-LAST:event_DTPTglItemStateChanged

    private void DTPTglMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTPTglMouseClicked

    }//GEN-LAST:event_DTPTglMouseClicked

    private void DTPTglKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DTPTglKeyPressed
//        Valid.pindah(evt, TNoRw, CmbJam);
    }//GEN-LAST:event_DTPTglKeyPressed

    private void CmbJamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbJamKeyPressed
//        Valid.pindah(evt, DTPReg, CmbMenit);
    }//GEN-LAST:event_CmbJamKeyPressed

    private void CmbMenitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbMenitKeyPressed
        Valid.pindah(evt, CmbJam, CmbDetik);
    }//GEN-LAST:event_CmbMenitKeyPressed

    private void CmbDetikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CmbDetikKeyPressed
//        Valid.pindah(evt, CmbMenit, kddokter);
    }//GEN-LAST:event_CmbDetikKeyPressed

    private void cmbJenisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbJenisItemStateChanged
        if (chkSemua.isSelected() == false) {
            switch (cmbJenis.getSelectedIndex()) {
                case 0:
                case 1:
                case 2:
                    DTPTgl.setVisible(true);
                    CmbJam.setVisible(true);
                    CmbMenit.setVisible(true);
                    CmbDetik.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel12.setVisible(true);
                    noresep.setVisible(true);
                    break;
                case 3:
                case 4:
                case 5:
                case 6:
                    DTPTgl.setVisible(true);
                    CmbJam.setVisible(true);
                    CmbMenit.setVisible(true);
                    CmbDetik.setVisible(true);
                    jLabel8.setVisible(true);
                    jLabel9.setVisible(true);
                    jLabel12.setVisible(false);
                    noresep.setVisible(false);
                    break;
                case 7:
                case 8:
                case 9:
                    DTPTgl.setVisible(false);
                    CmbJam.setVisible(false);
                    CmbMenit.setVisible(false);
                    CmbDetik.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel12.setVisible(false);
                    noresep.setVisible(false);
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_cmbJenisItemStateChanged

    private void cmbJenisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbJenisKeyPressed
//        Valid.pindah(evt, btnDPJP, Kelas);
    }//GEN-LAST:event_cmbJenisKeyPressed

    private void chkSemuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSemuaActionPerformed
        if (chkSemua.isSelected() == true) {
            DTPTgl.setVisible(false);
            CmbJam.setVisible(false);
            CmbMenit.setVisible(false);
            CmbDetik.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel12.setVisible(false);
            noresep.setVisible(false);
        }
        if (chkSemua.isSelected() == false) {
            DTPTgl.setVisible(true);
            CmbJam.setVisible(true);
            CmbMenit.setVisible(true);
            CmbDetik.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel12.setVisible(true);
            noresep.setVisible(true);
        }
    }//GEN-LAST:event_chkSemuaActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        chkSemua.setSelected(false);
        isKosong();
    }//GEN-LAST:event_BtnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgPindahRiwPasien dialog = new DlgPindahRiwPasien(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnBatal;
    private widget.Button BtnCek;
    private widget.Button BtnKeluar;
    private widget.Button BtnKeluar1;
    private widget.ComboBox CmbDetik;
    private widget.ComboBox CmbJam;
    private widget.ComboBox CmbMenit;
    private widget.Tanggal DTPTgl;
    private widget.TextBox NoRwDari;
    private widget.TextBox NoRwKe;
    private widget.CekBox chkSemua;
    private widget.ComboBox cmbJenis;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel10;
    private widget.Label jLabel11;
    private widget.Label jLabel12;
    private widget.Label jLabel3;
    private widget.Label jLabel4;
    private widget.Label jLabel5;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private widget.Label jLabel8;
    private widget.Label jLabel9;
    private widget.TextBox noresep;
    private widget.panelisi panelGlass7;
    private widget.TextArea pesan;
    private widget.TextArea pesan1;
    private widget.ScrollPane scrollPane1;
    private widget.ScrollPane scrollPane2;
    // End of variables declaration//GEN-END:variables

    public String cekSttsBayar(String norawat) {
        String cek = Sequel.cariIsi("SELECT status_bayar FROM reg_periksa WHERE no_rawat=?", norawat);
        return cek;
    }

    public String cekPasien(String norawat) {
        String cek = Sequel.cariIsi("SELECT no_rawat FROM reg_periksa WHERE no_rawat=?", norawat);
        return cek;
    }

    public String cekData(String norawat) {
        String cek = Sequel.cariIsi("SELECT GROUP_CONCAT('No.RM: ',pasien.no_rkm_medis,'\n', 'Pasien: ',pasien.nm_pasien,'\n','Tgl. Registrasi: ',reg_periksa.tgl_registrasi,'\n', 'Jam: ',jam_reg) as pasien "
                + "FROM reg_periksa INNER JOIN pasien ON reg_periksa.no_rkm_medis=pasien.no_rkm_medis WHERE reg_periksa.no_rawat=?", norawat);
        return cek;
    }

    private void isKosong() {
        NoRwDari.setText("");
        NoRwKe.setText("");
        pesan.setText("");
        pesan1.setText("");
    }

    private void isSemua() {
        jLabel8.setVisible(false);
        DTPTgl.setVisible(false);
        CmbJam.setVisible(false);
        CmbMenit.setVisible(false);
        CmbDetik.setVisible(false);
        jLabel12.setVisible(false);
        noresep.setVisible(false);
    }

    private void pindahAll() {
        switch (cmbJenis.getSelectedItem().toString().substring(0, 1)) {
            case "1":
                Sequel.queryu2("UPDATE resep_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND status='ralan' limit 20");
                Sequel.queryu2("UPDATE detail_pemberian_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND status ='Ralan' limit 50");
                Sequel.queryu2("UPDATE aturan_pakai SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' limit 50");
                JOptionPane.showMessageDialog(null, "Berhasil pindah resep obat ralan...");
                break;
            case "2":
                Sequel.queryu2("UPDATE resep_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND status='ranap' limit 20");
                Sequel.queryu2("UPDATE detail_pemberian_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND status ='Ranap' limit 50");
                Sequel.queryu2("UPDATE aturan_pakai SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' limit 50");
                Sequel.queryu2("UPDATE jurnal SET no_bukti='" + NoRwKe.getText().trim() + "' WHERE no_bukti='" + NoRwDari.getText().trim() + "' AND KETERANGAN like 'PEMBERIAN OBAT RAWAT INAP PASIEN%' limit 50");
                JOptionPane.showMessageDialog(null, "Berhasil pindah resep obat ranap...");
                break;
            case "3":
                Sequel.queryu2("UPDATE resep_pulang SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' limit 20");
                Sequel.queryu2("UPDATE detail_pemberian_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND status ='Pulang' limit 50");
                Sequel.queryu2("UPDATE jurnal SET no_bukti='" + NoRwKe.getText().trim() + "' WHERE no_bukti='" + NoRwDari.getText().trim() + "' AND KETERANGAN like 'RESEP PULANG RAWAT INAP PASIEN%' limit 50");
                JOptionPane.showMessageDialog(null, "Berhasil pindah resep pulang...");
                break;
            case "4":
                Sequel.queryu2("UPDATE pemeriksaan_ralan SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 50");
                JOptionPane.showMessageDialog(null, "Berhasil pindah SOAP ralan...");
                break;
            case "5":
                Sequel.queryu2("UPDATE pemeriksaan_ranap SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 50");
                JOptionPane.showMessageDialog(null, "Berhasil pindah SOAP ranap...");
                break;
            case "6":
                Sequel.queryu2("UPDATE permintaan_lab SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 20");
                Sequel.queryu2("UPDATE periksa_lab SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 50");
                Sequel.queryu2("UPDATE detail_periksa_lab SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 100");
                JOptionPane.showMessageDialog(null, "Berhasil pindah hasil laboratorium..");
                break;
            case "7":
                Sequel.queryu2("UPDATE permintaan_radiologi SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 20");
                Sequel.queryu2("UPDATE periksa_radiologi SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 20");
                Sequel.queryu2("UPDATE beri_bhp_radiologi SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 20");
                Sequel.queryu2("UPDATE hasil_radiologi SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 20");
                Sequel.queryu2("UPDATE saran_kesan_rad SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 20");
                JOptionPane.showMessageDialog(null, "Berhasil pindah hasil radiologi..");
                break;
            case "8":
                Sequel.queryu2("UPDATE reg_periksa SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 1");
                JOptionPane.showMessageDialog(null, "Berhasil pindah registrasi..");
                break;
            case "9":
                Sequel.queryu2("UPDATE bridging_sep SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 1");
                JOptionPane.showMessageDialog(null, "Berhasil pindah SEP..");
                break;
            case "10":
                Sequel.queryu2("UPDATE bridging_surat_pri_bpjs SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 1");
                JOptionPane.showMessageDialog(null, "Berhasil pindah SPRI..");
                break;
            case "11":
                Sequel.queryu2("UPDATE data_triase_igd SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 1");
                Sequel.queryu2("UPDATE detail_pemeriksaan_triase SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 10");
                JOptionPane.showMessageDialog(null, "Berhasil pindah triage IGD..");
                break;
            case "12":
                Sequel.queryu2("UPDATE rawat_jl_dr SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 10");
                JOptionPane.showMessageDialog(null, "Berhasil pindah tindakan dokter ralan..");
                break;
            case "13":
                Sequel.queryu2("UPDATE rawat_jl_pr SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 10");
                JOptionPane.showMessageDialog(null, "Berhasil pindah tindakan paramedis ralan..");
                break;
            default:
                break;
        }
    }

    private void pindah() {
        String tgl = Valid.SetTgl(DTPTgl.getSelectedItem() + "");
        String jam = CmbJam.getSelectedItem().toString() + ":" + CmbMenit.getSelectedItem().toString() + ":" + CmbDetik.getSelectedItem().toString();
        switch (cmbJenis.getSelectedItem().toString().substring(0, 1)) {
            case "1":
                Sequel.queryu2("UPDATE resep_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND no_resep='" + noresep.getText() + "' AND status='ralan' LIMIT 1");
                Sequel.queryu2("UPDATE detail_pemberian_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND tgl_perawatan='" + tgl + "' AND jam='" + jam + "' AND status ='Ralan' LIMIT 50");
                Sequel.queryu2("UPDATE aturan_pakai SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND tgl_perawatan='" + tgl + "' AND jam='" + jam + "' LIMIT 50");
                JOptionPane.showMessageDialog(null, "Berhasil pindah resep obat ralan...");
                break;
            case "2":
                Sequel.queryu2("UPDATE resep_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND no_resep='" + noresep.getText() + "' AND status='ranap' LIMIT 1");
                Sequel.queryu2("UPDATE detail_pemberian_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND tgl_perawatan='" + tgl + "' AND jam='" + jam + "' AND status ='Ranap' LIMIT 50");
                Sequel.queryu2("UPDATE aturan_pakai SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND tgl_perawatan='" + tgl + "' AND jam='" + jam + "' LIMIT 50");
                Sequel.queryu2("UPDATE jurnal SET no_bukti='" + NoRwKe.getText().trim() + "' WHERE no_bukti='" + NoRwDari.getText().trim() + "' AND KETERANGAN like 'PEMBERIAN OBAT RAWAT INAP PASIEN%' LIMIT 1");
                JOptionPane.showMessageDialog(null, "Berhasil pindah resep obat ranap...");
                break;
            case "3":
                Sequel.queryu2("UPDATE resep_pulang SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND no_resep='" + noresep.getText() + "' limit 1");
                Sequel.queryu2("UPDATE detail_pemberian_obat SET no_rawat='" + NoRwKe.getText().trim() + "' WHERE no_rawat='" + NoRwDari.getText().trim() + "' AND tgl_perawatan='" + tgl + "' AND jam='" + jam + "' AND status ='Pulang' limit 50");
                Sequel.queryu2("UPDATE jurnal SET no_bukti='" + NoRwKe.getText().trim() + "' WHERE no_bukti='" + NoRwDari.getText().trim() + "' AND tgl_perawatan='" + tgl + "' AND jam='" + jam + "' AND KETERANGAN like 'RESEP PULANG RAWAT INAP PASIEN%' limit 50");
                JOptionPane.showMessageDialog(null, "Berhasil pindah resep pulang...");
                break;
            case "4":
                Sequel.queryu2("UPDATE pemeriksaan_ralan SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' AND tgl_perawatan='" + tgl + "' AND jam_rawat='" + jam + "' LIMIT 1");
                JOptionPane.showMessageDialog(null, "Berhasil pindah SOAP ralan...");
                break;
            case "5":
                Sequel.queryu2("UPDATE pemeriksaan_ranap SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' AND tgl_perawatan='" + tgl + "' AND jam_rawat='" + jam + "' LIMIT 1");
                JOptionPane.showMessageDialog(null, "Berhasil pindah SOAP ranap...");
                break;
            case "6":
                Sequel.queryu2("UPDATE permintaan_lab SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' AND tgl_hasil='" + tgl + "' AND jam_hasil='" + jam + "' LIMIT 1");
                Sequel.queryu2("UPDATE periksa_lab SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "'  AND tgl_periksa='" + tgl + "' AND jam='" + jam + "' LIMIT 50");
                JOptionPane.showMessageDialog(null, "Berhasil pindah hasil laboratorium..");
                break;
            case "7":
                Sequel.queryu2("UPDATE permintaan_radiologi SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' AND tgl_hasil='" + tgl + "' AND jam_hasil='" + jam + "' LIMIT 1");
                Sequel.queryu2("UPDATE periksa_radiologi SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' AND tgl_periksa='" + tgl + "' AND jam='" + jam + "' LIMIT 20");
                Sequel.queryu2("UPDATE beri_bhp_radiologi SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' AND tgl_periksa='" + tgl + "' AND jam='" + jam + "' LIMIT 20");
                Sequel.queryu2("UPDATE hasil_radiologi SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' AND tgl_periksa='" + tgl + "' AND jam='" + jam + "' LIMIT 20");
                Sequel.queryu2("UPDATE saran_kesan_rad SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' AND tgl_periksa='" + tgl + "' AND jam='" + jam + "' LIMIT 20");
                JOptionPane.showMessageDialog(null, "Berhasil pindah hasil radiologi..");
                break;
            case "8":
                Sequel.queryu2("UPDATE reg_periksa SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 1");
                JOptionPane.showMessageDialog(null, "Berhasil pindah registrasi..");
                break;
            case "9":
                Sequel.queryu2("UPDATE bridging_sep SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 1");
                JOptionPane.showMessageDialog(null, "Berhasil pindah SEP..");
                break;
            case "10":
                Sequel.queryu2("UPDATE bridging_surat_pri_bpjs SET no_rawat='" + NoRwKe.getText() + "' WHERE no_rawat='" + NoRwDari.getText() + "' LIMIT 1");
                JOptionPane.showMessageDialog(null, "Berhasil pindah SPRI..");
                break;
            default:
                break;
        }
    }
}
