/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simrskhanza;

import fungsi.WarnaTable;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.var;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.HyperlinkEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;
import javax.swing.text.html.StyleSheet;

/**
 *
 * @author khanzamedia
 */
public class PanelResume2 extends widget.panelisi {

    private final Connection koneksi = koneksiDB.condb();
    private DefaultTableModel tabModeRegistrasi;
    private final sekuel Sequel = new sekuel();
    private final Properties prop = new Properties();
    private validasi Valid = new validasi();
    private ResultSet rs, rs2, rs3, rs4, rshal;
    private PreparedStatement ps, ps2;
    private String sql, tanggal = "", jam = "", dpjp = "", kddpjp = "", tanggal1 = "", tanggal2 = "", norm = "", limit = "", additional = "", norawat = "";
    private StringBuilder htmlContent;
    private boolean caritanggal = false;
    private int i = 0, y = 0, w = 0, urut;

    /**
     * Creates new form PanelResume
     */
    public PanelResume2() {
        initComponents();

        try {
            prop.loadFromXML(new FileInputStream("setting/database.xml"));
        } catch (Exception e) {
            System.out.println("Resume : " + e);
        }

        HTMLEditorKit kit = new HTMLEditorKit();
        LoadHTML.setEditorKit(kit);

        StyleSheet styleSheet = kit.getStyleSheet();
        styleSheet.addRule(".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#464646;}.isi a{text-decoration:none;color:#8b9b95;padding:0 0 0 0px;font-family: Tahoma;font-size: 8.5px;}");
        Document doc = kit.createDefaultDocument();
        LoadHTML.setDocument(doc);
        LoadHTML.setEditable(false);

        LoadHTML.addHyperlinkListener(e -> {
            if (HyperlinkEvent.EventType.ACTIVATED.equals(e.getEventType())) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    desktop.browse(e.getURL().toURI());
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame2 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        LoadHTML = new widget.editorpane();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        internalFrame2.setBackground(new java.awt.Color(255, 255, 255));
        internalFrame2.setBorder(null);
        internalFrame2.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Scroll.setOpaque(true);

        LoadHTML.setBorder(null);
        Scroll.setViewportView(LoadHTML);

        internalFrame2.add(Scroll, java.awt.BorderLayout.CENTER);

        add(internalFrame2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.editorpane LoadHTML;
    private widget.ScrollPane Scroll;
    private widget.InternalFrame internalFrame2;
    // End of variables declaration//GEN-END:variables
    public void tampil(){     
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try{
            htmlContent = new StringBuilder();
            try {
                rs=koneksi.prepareStatement("select kamar_inap.no_rawat, reg_periksa.no_rkm_medis, pasien.nm_pasien, pasien.tgl_lahir, kamar_inap.tgl_masuk,kamar_inap.jam_masuk, kamar_inap.tgl_keluar, kamar_inap.jam_keluar, concat(kamar_inap.kd_kamar,' ',bangsal.nm_bangsal) as kamar, kamar.kelas, penjab.png_jawab "
                        + "from kamar_inap,reg_periksa,pasien,kamar,bangsal,penjab "
                        + "where kamar_inap.no_rawat=reg_periksa.no_rawat and reg_periksa.no_rkm_medis=pasien.no_rkm_medis and kamar_inap.kd_kamar=kamar.kd_kamar and kamar.kd_bangsal=bangsal.kd_bangsal and reg_periksa.kd_pj=penjab.kd_pj "
                        + "and kamar_inap.stts_pulang <> 'Pindah Kamar' and kamar_inap.no_rawat='" + norawat + "'").executeQuery();
                y=1;
                while(rs.next()){   
                    htmlContent.append(
                            "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"
                            + "<tr class='isi'>"
                            + "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. RM</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' width='24%' >" + rs.getString("no_rkm_medis") + "</td>"
                            + "<td valign='top' width='20%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tanggal Masuk</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' width='15%' >" + rs.getString("tgl_masuk") + "</td>"
                            + "<td valign='top' width='7%'>Jam</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' width='6%' >" + rs.getString("jam_masuk") + "</td>"
                            + "</tr>"
                            + "<tr class='isi'>"
                            + "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pasien</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' width='24%' >" + rs.getString("nm_pasien") + "</td>"
                            + "<td valign='top' width='20%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tanggal Keluar</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' width='15%' >" + rs.getString("tgl_keluar") + "</td>"
                            + "<td valign='top' width='7%'>Jam</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' width='6%' >" + rs.getString("jam_keluar") + "</td>"
                            + "</tr>"
                            + "<tr class='isi'>"
                            + "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lahir</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' width='24%' >" + rs.getString("tgl_lahir") + "</td>"
                            + "<td valign='top' width='20%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ruang Rawat Terakhir</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' colspan='4'>" + rs.getString("kamar") + "</td>"
                            + "</tr>"
                            + "<tr class='isi'>"
                            + "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Bayar</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' width='24%' >" + rs.getString("png_jawab") + "</td>"
                            + "<td valign='top' width='20%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kelas</td>"
                            + "<td valign='top' width='1%' align='center'>:</td>"
                            + "<td valign='top' colspan='4'>" + rs.getString("kelas") + "</td>"
                            + "</tr>");
                    try {
                        rs2 = koneksi.prepareStatement(
                                "select diagnosa_utama,jalannya_penyakit,pemeriksaan_fisik,pemeriksaan_penunjang,hasil_laborat, "
                                +"keluhan_utama,diagnosa_awal, prosedur_utama,obat_di_rs,obat_pulang, "
//                                +"(SELECT GROUP_CONCAT(kd_penyakit order by cast(prioritas as unsigned)) from diagnosa_pasien where diagnosa_pasien.no_rawat='" + rs.getString("no_rawat") + "' and diagnosa_pasien.status='Ranap') as icdx "
                                +"(SELECT GROUP_CONCAT(kd_diagnosa_utama,kd_diagnosa_sekunder,kd_diagnosa_sekunder2,kd_diagnosa_sekunder3,kd_diagnosa_sekunder4) from resume_pasien_ranap where no_rawat='" + rs.getString("no_rawat") + "') as icdx "
                                +"from resume_pasien_ranap where no_rawat='" + rs.getString("no_rawat") + "'").executeQuery();                            
                        urut=1;
                        while(rs2.next()){      
                            htmlContent.append(
                              "<tr class='isi'>"+ 
                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Diagnosa Masuk</td>"+
                                "<td valign='top' width='1%' align='center'>:</td>"+
                                "<td valign='top' colspan='7'>"+rs2.getString("diagnosa_utama")+"</td>"+
                              "</tr>"+
                              "<tr class='isi'>"+ 
                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ringkasan Riwayat Penyakit</td>"+
                                "<td valign='top' width='1%' align='center'>:</td>"+
                                "<td valign='top' colspan='7'>"+rs2.getString("jalannya_penyakit")+"</td>"+
                              "</tr>"+
                              "<tr class='isi'>"+ 
                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pemeriksaan Fisik</td>"+
                                "<td valign='top' width='1%' align='center'>:</td>"+
                                "<td valign='top' colspan='7'>"+rs2.getString("pemeriksaan_fisik").replace("\n", "<br>")+"</td>"+
                              "</tr>"+
                              "<tr class='isi'>"+ 
                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pemeriksaan Penunjang Yang Penting</td>"+
                                "<td valign='top' width='1%' align='center'>:</td>"+
                                "<td valign='top' colspan='7'>"+rs2.getString("pemeriksaan_penunjang").replace("\n", "<br>")+"</td>"+
                              "</tr>"+
                              "<tr class='isi'>"+ 
                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pemeriksaan Laboratorium</td>"+
                                "<td valign='top' width='1%' align='center'>:</td>"+
                                "<td valign='top' colspan='7'>"+rs2.getString("hasil_laborat").replace("\n", "<br>")+"</td>"+
                              "</tr>"+
                              "<tr class='isi'>"+ 
                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Keluhan Utama</td>"+
                                "<td valign='top' width='1%' align='center'>:</td>"+
                                "<td valign='top' colspan='7'>"+rs2.getString("keluhan_utama")+"</td>"+
                              "</tr>"+
                               "<tr class='isi'>"
                                    + "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Diagnosa Utama</td>"
                                    + "<td valign='top' width='1%' align='center'>:</td>"
                                    + "<td valign='top' width='60%' colspan='4'>" + rs2.getString("diagnosa_utama") + "</td>"
                                    + "<td valign='top' width='7%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ICD X</td>"
                                    + "<td valign='top' width='1%' align='center'>:</td>"
                                    +"<td valign='top' width='6%' >" + rs2.getString("icdx") + "</td>"
                                    + "</tr>"
//                              "<tr class='isi'>"+ 
//                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Diagnosa Utama</td>"+
//                                "<td valign='top' width='1%' align='center'>:</td>"+
//                                "<td valign='top' colspan='7'>"+rs2.getString("diagnosa_awal")+"</td>"+
//                              "</tr>"+
                              +"<tr class='isi'>"+ 
                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Prosedur Utama</td>"+
                                "<td valign='top' width='1%' align='center'>:</td>"+
                                "<td valign='top' colspan='7'>"+rs2.getString("prosedur_utama")+"</td>"+
                              "</tr>"+
                              "<tr class='isi'>"+ 
                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Terapi</td>"+
                                "<td valign='top' width='1%' align='center'>:</td>"+
                                "<td valign='top' colspan='7'>"+rs2.getString("obat_di_rs").replace("\n", "<br>")+"</td>"+
                              "</tr>"+
                              "<tr class='isi'>"+ 
                                "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Terapi Pulang</td>"+
                                "<td valign='top' width='1%' align='center'>:</td>"+
                                "<td valign='top' colspan='7'>"+rs2.getString("obat_pulang").replace("\n", "<br>")+"</td>"+
                              "</tr>"
                            );                            
                            urut++;
                            
                            htmlContent.append(
                               "<tr class='isi'>"+ 
                                 "<td valign='top' width='25%'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Diagnosa Utama</td>"+
                                 "<td valign='top' width='1%' align='center'>:</td>"+
                                 "<td valign='top' width='74%'>"
                            );
//                            tindakan dokter ralan
//                            try{
//                                rs3=koneksi.prepareStatement(
//                                    "select diagnosa_utama, kd_diagnosa_utama, diagnosa_sekunder, kd_diagnosa_sekunder,diagnosa_sekunder2, kd_diagnosa_sekunder2, diagnosa_sekunder3, kd_diagnosa_sekunder3, "
//                                    + "diagnosa_sekunder4, kd_diagnosa_sekunder4 from resume_pasien_ranap where no_rawat='"+rs.getString("no_rawat")+"'").executeQuery();
//                                if(rs3.next()){                                    
//                                    htmlContent.append(  
//                                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
//                                        "<tr><td valign='top' colspan='4'>Tindakan Rawat Jalan Dokter</td><td valign='top' colspan='1' align='right'>:</td><td valign='top'></td></tr>"+
//                                        "<tr align='center'>"+
//                                          "<td valign='top' width='5%' bgcolor='#fafff5'>No.</td>"+
//                                          "<td valign='top' width='15%' bgcolor='#fafff5'>Tanggal</td>"+
//                                          "<td valign='top' width='10%' bgcolor='#fafff5'>Kode</td>"+
//                                          "<td valign='top' width='40%' bgcolor='#fafff5'>Nama Tindakan/Perawatan</td>"+
//                                          "<td valign='top' width='20%' bgcolor='#fafff5'>Dokter</td>"+
//                                          "<td valign='top' width='10%' bgcolor='#fafff5'>Biaya</td>"+
//                                        "</tr>");
//                                    rs3.beforeFirst();
//                                    w=1;
//                                    while(rs3.next()){
//                                        htmlContent.append(
//                                             "<tr>"+
//                                                "<td valign='top' align='center'>"+w+"</td>"+
//                                                "<td valign='top'>"+rs3.getString("tgl_perawatan")+" "+rs3.getString("jam_rawat")+"</td>"+
//                                                "<td valign='top'>"+rs3.getString("kd_jenis_prw")+"</td>"+
//                                                "<td valign='top'>"+rs3.getString("nm_perawatan")+"</td>"+
//                                                "<td valign='top'>"+rs3.getString("nm_dokter")+"</td>"+
//                                                "<td valign='top' align='right'>"+Valid.SetAngka(rs3.getDouble("biaya_rawat"))+"</td>"+
//                                             "</tr>"); 
//                                        w++;
//                                    }
//                                    htmlContent.append(
//                                      "</table>");
//                                }                                
//                            } catch (Exception e) {
//                                System.out.println("Notifikasi : "+e);
//                            } finally{
//                                if(rs3!=null){
//                                    rs3.close();
//                                }
//                            }
                            
                            htmlContent.append(                                    
                                 "</td>"+
                               "</tr>"                               
                            );
                            htmlContent.append("<tr class='isi'><td colspan='3'>&nbsp;</td></tr>");
                        }
                    } catch (Exception e) {
                        System.out.println("Notifikasi : "+e);
                    } finally{
                        if(rs2!=null){
                            rs2.close();
                        }
                    }
                    y++;
                }
                LoadHTML.setText(
                    "<html>"+
                      "<table width='100%' border='0' align='center' cellpadding='3px' cellspacing='0' class='tbl_form'>"+
                       htmlContent.toString()+
                      "</table>"+
                    "</html>");
            } catch (Exception e) {
                System.out.println("Notifikasi : "+e);
            } finally{
                if(rs!=null){
                    rs.close();
                }
            }
            
        }catch(Exception e){
            System.out.println("Notifikasi : "+e);
        }
        this.setCursor(Cursor.getDefaultCursor());
    }

    private void panggilLaporan(String teks) {
        try {
            File g = new File("file.css");
            BufferedWriter bg = new BufferedWriter(new FileWriter(g));
            bg.write(".isi td{border-right: 1px solid #e2e7dd;font: 8.5px tahoma;height:12px;border-bottom: 1px solid #e2e7dd;background: #ffffff;color:#464646;}.isi a{text-decoration:none;color:#8b9b95;padding:0 0 0 0px;font-family: Tahoma;font-size: 8.5px;}");
            bg.close();

            File f = new File("resumemedis.html");
            BufferedWriter bw = new BufferedWriter(new FileWriter(f));
            bw.write(teks.replaceAll(
                    "<head>", "<head><link href=\"file.css\" rel=\"stylesheet\" type=\"text/css\" />")
            );
            bw.close();
            Desktop.getDesktop().browse(f.toURI());
        } catch (Exception e) {
            System.out.println("Notifikasi : " + e);
        }
    }

    public void setRM(String norawat, String norm) {
        this.norawat = norawat;
        this.norm = norm;
        tampil();
    }

    public void laporan() {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        panggilLaporan(LoadHTML.getText());
    }
}
